route:
  group_by: [Alertname]
  # Setup to send all notification over mail.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: anyemail.com
    from: senderlogin@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "senderlogin@gmail.com"
    auth_identity: "senderlogin@gmail.com"
    auth_password: "password"